# Set catalog URL for resources to be uploaded to
catalog_url: https://localhost/catalog/e73fa363-7ce9-4ee1-accf-78370164b529

# Set location of FDP metadata CSV sheets if they are used 
dataset_file: "test-input/datasets.csv"
distribution: "test-input/distributions.csv"

# Set location of EJPRD metadata Excel sheet if it is used instead of the FDP metadata
ejp_vp_file: "vp_test_input/dataset_test_complete.xlsx"

# Set dry run to true to test FDPP before uploading metadata
dry_run: false

# Set debug to false to disable debug messages
debug: true